package it.grational

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author d7392
 * @date 08-12-2020 07.32
 */
class LibrarySpec extends Specification {
	def "someLibraryMethod returns true"() {
		setup:
			Library lib = new Library()
		when:
			Boolean result = lib.someLibraryMethod()
		then:
			result == true
	}
}
